import type { PartnerBrand } from './types';

export const PARTNER_BRANDS: PartnerBrand[] = [
  {
    id: 'lotus-mart',
    name: 'Lotus Mart',
    symbol: 'LTM',
    category: 'Supermarket & Retail',
    categoryVi: 'Siêu thị & Bán lẻ tiêu dùng',
    color: '#9f0261',
    stores: 64,
    activeMembers: '28,400',
    pointsRate: '10,000 ₫ = 1 Petal',
    pointsRateVi: '10.000 ₫ = 1 Sen (Điểm)',
    description: 'National grocery chain providing member tiers, fresh market vouchers, and instant barcode point issuance at checkout.',
    descriptionVi: 'Chuỗi siêu thị thực phẩm toàn quốc tích điểm tức thì tại quầy thu ngân, phân hạng thành viên và đổi phiếu ưu đãi.',
    moveModule: '0x8f2a...ltm::loyalty',
  },
  {
    id: 'pho-ca-phe',
    name: 'Phố Cà Phê',
    symbol: 'PCP',
    category: 'Artisan Coffee & Bakery',
    categoryVi: 'Chuỗi cà phê thủ công & bánh',
    color: '#8b5a2b',
    stores: 42,
    activeMembers: '19,200',
    pointsRate: '20,000 ₫ = 1 Coffee Bean',
    pointsRateVi: '20.000 ₫ = 1 Hạt Cà Phê',
    description: 'High-frequency beverage loyalty with seasonal specialty drink redemption and AI-driven barista recommendations.',
    descriptionVi: 'Hệ thống tích điểm đồ uống với voucher trà bánh theo mùa và tích hợp đề xuất đồ uống qua AI.',
    moveModule: '0x3c7e...pcp::loyalty',
  },
  {
    id: 'saigon-books',
    name: 'Sài Gòn Books',
    symbol: 'SGB',
    category: 'Publishing & Bookstore',
    categoryVi: 'Nhà sách & Xuất bản phẩm',
    color: '#002b49',
    stores: 18,
    activeMembers: '14,800',
    pointsRate: '15,000 ₫ = 1 Bookmark',
    pointsRateVi: '15.000 ₫ = 1 Dấu Trang',
    description: 'Cultural community loyalty offering author meet-and-greet passes, workshop vouchers, and signed edition rewards.',
    descriptionVi: 'Cộng đồng đọc sách văn hóa với vé tham dự buổi ra mắt sách tác giả, workshop và phiên bản giới hạn.',
    moveModule: '0x991f...sgb::loyalty',
  },
  {
    id: 'mekong-fitness',
    name: 'Mekong Fitness',
    symbol: 'MEK',
    category: 'Health & Wellness Clubs',
    categoryVi: 'Trung tâm Thể hình & Yoga',
    color: '#5d8f2c',
    stores: 12,
    activeMembers: '9,600',
    pointsRate: '1 Check-in = 50 Active Miles',
    pointsRateVi: '1 Lần Check-in = 50 Dặm Thể Lực',
    description: 'Gamified physical fitness rewards unlocking personal trainer sessions, sauna day passes, and protein recovery snacks.',
    descriptionVi: 'Tích điểm theo tần suất tập luyện để đổi buổi huấn luyện viên cá nhân, vé xông hơi và nước dinh dưỡng.',
    moveModule: '0x44d1...mek::loyalty',
  },
  {
    id: 'sunrise-hotels',
    name: 'Sunrise Hotels',
    symbol: 'SNH',
    category: 'Boutique Resorts & Travel',
    categoryVi: 'Khách sạn nghỉ dưỡng ven biển',
    color: '#f39c12',
    stores: 8,
    activeMembers: '6,200',
    pointsRate: '50,000 ₫ = 1 Sunset Star',
    pointsRateVi: '50.000 ₫ = 1 Sao Hoàng Hôn',
    description: 'Luxury hospitality loyalty featuring room upgrade certificates, rooftop lounge cocktails, and spa wellness credits.',
    descriptionVi: 'Chương trình tri ân khách sạn cao cấp hỗ trợ nâng hạng phòng nghỉ, đồ uống lounge và ưu đãi spa.',
    moveModule: '0x62a8...snh::loyalty',
  },
];

export const DICTIONARY = {
  en: {
    nav: {
      features: 'Features',
      whyOctap: 'Why OctaP',
      architecture: 'Architecture',
      developers: 'Developers',
      ecosystem: 'Partners',
      calculator: 'ROI Calculator',
      faq: 'FAQ',
      login: 'Sign In',
      wallet: 'Try Wallet Demo',
      dashboard: 'Open Console',
      demoAccounts: 'Demo Accounts',
    },
    hero: {
      badge: 'Enterprise Credit-as-a-Service (CaaS) on Sui',
      h1Lead: 'The Fraud-Proof Loyalty',
      h1Accent: 'Infrastructure',
      h1Tail: 'for Modern Enterprises.',
      description:
        'Deploy tenant-isolated, cryptographically auditable reward tokens in minutes. Eliminate internal point manipulation, slash reconciliation disputes to zero, and deliver a frictionless Web2 experience powered by Sui zkLogin and sponsored transactions.',
      ctaPrimary: 'Explore Merchant Console',
      ctaSecondary: 'Try Consumer Wallet',
      ctaDocs: 'View SDK & MCP Docs',
      subtext: 'No crypto wallets required · Sub-second finality · 100% sponsored gas fees',
      liveSimulatorTitle: 'Live POS & Consensus Simulation',
      merchantSelectLabel: 'Select Enterprise Merchant',
      customerPhoneLabel: 'Customer Phone (zkLogin)',
      billAmountLabel: 'Checkout Bill Amount (₫)',
      btnSimulate: 'Simulate POS Point Mint',
      minting: 'Executing on Sui...',
      resultIssued: 'Points Minted on Sui Move',
      suiTxStreamTitle: 'Live Sui Ledger Activity',
      sponsoredTag: 'Sponsored Gas: 0 SUI',
      verifiedDigest: 'Verified Digest',
      clickToVerify: 'Click to inspect on-chain proof',
    },
    metrics: {
      isolationVal: '100%',
      isolationLbl: 'Tenant Isolation',
      isolationSub: 'Strict object separation per merchant',
      finalityVal: '<400ms',
      finalityLbl: 'Consensus Finality',
      finalitySub: 'Sub-second checkout confirmation',
      gasVal: '0 ₫',
      gasLbl: 'End-User Gas Cost',
      gasSub: 'Fully sponsored platform transactions',
      fraudVal: '0%',
      fraudLbl: 'Internal Database Fraud',
      fraudSub: 'Cryptographic ledger immutability',
      integrationVal: '15 min',
      integrationLbl: 'POS Integration Time',
      integrationSub: 'Turnkey TypeScript SDK & REST API',
    },
    why: {
      secNum: '01',
      title: 'The Shift to Cryptographic Loyalty',
      subtitle:
        'Centralized databases suffer from silent point manipulation, employee fraud, and opaque partner reconciliation. Traditional Web3 solutions create unacceptable friction. OctaP bridges the gap.',
      tableTitle: 'Comparative Infrastructure Breakdown',
      colFeature: 'Capability',
      colTrad: 'Traditional Centralized DB',
      colUrbox: 'B2C Voucher Marketplaces',
      colTalon: 'Web2 Promotion SaaS',
      colOctap: 'OctaP CaaS (Sui Blockchain)',
      features: [
        {
          name: 'Ledger Auditability',
          trad: 'Opaque internal SQL logs; easily altered by DB admins',
          urbox: 'Closed platform database; partners must trust central ledger',
          talon: 'Proprietary audit trail; vulnerable to DB manipulation',
          octap: 'Public cryptographic Sui digests; mathematical immutability',
        },
        {
          name: 'Tenant Point Isolation',
          trad: 'Complex custom table schemas; risk of point leakage',
          urbox: 'Shared aggregator marketplace; lack of brand control',
          talon: 'Virtual rule engines; no cryptographic boundary',
          octap: 'Strict native Move Coin Objects per merchant treasury',
        },
        {
          name: 'End-User Experience',
          trad: 'App downloads, SMS OTP costs, forgot-password loops',
          urbox: 'Redirects to aggregator voucher app',
          talon: 'Custom merchant frontend required',
          octap: 'Zero Web3 friction: Phone / Google login via zkLogin',
        },
        {
          name: 'Transaction Costs',
          trad: 'Heavy cloud database & infrastructure licensing',
          urbox: 'High commission on every merchant voucher sale',
          talon: 'Costly enterprise monthly SaaS tier pricing',
          octap: 'Sub-penny Sui micro-gas fully sponsored by OctaP',
        },
        {
          name: 'AI Agent Context (MCP)',
          trad: 'None or custom manual API webhooks',
          urbox: 'No open AI agent integration',
          talon: 'REST webhooks only; no semantic agent state',
          octap: 'Native Model Context Protocol (MCP) server endpoints',
        },
        {
          name: 'Fiat Cash-Out Regulatory Risk',
          trad: 'Often contested in consumer protection audits',
          urbox: 'Restricted voucher catalog model',
          talon: 'Configurable business rules',
          octap: 'Strict non-transferable reward tokens; fully compliant',
        },
      ],
    },
    pillars: {
      secNum: '02',
      title: 'Architectural Pillars of OctaP',
      subtitle: 'Engineered from the ground up for enterprise reliability, high transaction throughput, and flawless cryptographic security.',
      items: [
        {
          id: 'isolation',
          tag: 'FE-01 · CORE ARCHITECTURE',
          title: 'Strict Object-Centric Tenant Isolation',
          desc: 'Each enterprise operates independent Move modules and point treasuries on the Sui blockchain. Lotus Mart points cannot cross over to Phố Cà Phê or dilute partner balance sheets. No fiat cash-out is permitted.',
          badge: 'Move Smart Contracts',
        },
        {
          id: 'zklogin',
          tag: 'FE-02 · SEAMLESS ADOPTION',
          title: 'Zero-Friction zkLogin & Sponsored Gas',
          desc: 'Consumers never manage private keys, seed phrases, or gas fees. Using Enoki zkLogin, a customer logs in with their existing phone number or Google account. OctaP sponsors 100% of network execution fees.',
          badge: 'Enoki zkLogin',
        },
        {
          id: 'pos',
          tag: 'FE-03 · HIGH-SPEED EARN',
          title: 'Automated POS & Sub-Second Issuance',
          desc: 'Award loyalty points at checkout counters in under 400 milliseconds. Built-in receipt barcode scanners and QR code generation allow cashiers to verify and mint points with zero line delays.',
          badge: 'POS & E-Commerce',
        },
        {
          id: 'mcp',
          tag: 'FE-04 · AI AUTOMATION',
          title: 'AI-Ready Model Context Protocol (MCP)',
          desc: 'Empower autonomous AI agents (Claude, Gemini, ChatGPT) to securely query member tiers, recommend personalized vouchers, and trigger campaign boosts within strictly enforced RBAC boundaries.',
          badge: 'Anthropic MCP Server',
        },
        {
          id: 'sdk',
          tag: 'FE-05 · DEVELOPER TOOLKIT',
          title: 'Turnkey TypeScript SDK & Webhooks',
          desc: 'Integrate existing ERP, POS systems, Shopify stores, and Flutter mobile apps with a 4-line TypeScript client. Includes built-in mock harnesses and sandbox testing tools.',
          badge: 'TypeScript SDK',
        },
        {
          id: 'audit',
          tag: 'FE-06 · COMPLIANCE & PROOF',
          title: 'Cryptographic Sui Audit Explorer',
          desc: 'Every point mint, campaign multiplier, voucher redemption, and admin adjustment produces a verifiable Sui transaction digest. Auditors verify state without accessing confidential customer PII.',
          badge: 'Immutable Verification',
        },
      ],
    },
    architecture: {
      secNum: '03',
      title: 'End-to-End Cryptographic Flow',
      subtitle: 'How OctaP transforms an everyday retail transaction into a cryptographically verified, zero-friction loyalty event.',
      steps: [
        {
          step: '1',
          title: 'Customer Checkout',
          actor: 'Consumer / Cashier',
          desc: 'Shopper presents phone number or scans receipt barcode at in-store POS register or online checkout.',
        },
        {
          step: '2',
          title: 'zkLogin Consent',
          actor: 'Enoki zkLogin Engine',
          desc: 'Zero-Knowledge authentication issues a short-lived cryptographic signature from phone or Google identity.',
        },
        {
          step: '3',
          title: 'OctaP CaaS Gateway',
          actor: 'API & MCP Engine',
          desc: 'Validates merchant campaign rules, tier multipliers (e.g. 1.5× Gold), and signs the sponsored gas envelope.',
        },
        {
          step: '4',
          title: 'Sui Blockchain Execution',
          actor: 'Move Isolated Coin Object',
          desc: 'Parallel consensus executes the mint or burn on the tenant’s isolated Move module in <400ms.',
        },
        {
          step: '5',
          title: 'Immutable Proof',
          actor: 'Public Sui Ledger Digest',
          desc: 'The transaction digest is permanently recorded for auditing, fraud prevention, and customer mobile wallet display.',
        },
      ],
    },
    developers: {
      secNum: '04',
      title: 'Developer Experience: SDK & MCP',
      subtitle: 'Build enterprise loyalty workflows in minutes with standard TypeScript or connect AI agents through the Model Context Protocol.',
      tabs: {
        earn: '1. POS Earn / Mint',
        redeem: '2. zkLogin Redeem',
        mcp: '3. AI Agent (MCP)',
        verify: '4. Ledger Verify',
      },
      btnRun: 'Execute SDK Simulation',
      outputTitle: 'SDK Response Payload (JSON)',
    },
    ecosystem: {
      secNum: '05',
      title: 'Active Partner Network',
      subtitle: 'Leading enterprises across grocery, retail, coffee, fitness, and hospitality running isolated loyalty tokens on OctaP.',
      badgeActive: 'Active Program',
      btnTestStore: 'View Store Prototype',
      tenantNotice: 'Strict Isolation Guarantee: Tokens are non-fungible across brands and cannot be converted to fiat currency.',
    },
    calculator: {
      secNum: '06',
      title: 'Interactive ROI & Fraud Savings Calculator',
      subtitle: 'Estimate annual savings achieved by switching from error-prone traditional databases to OctaP CaaS.',
      membersLabel: 'Monthly Active Loyalty Members',
      txsLabel: 'Monthly Point Transactions',
      basketLabel: 'Average Transaction Bill (₫)',
      resultsTitle: 'Estimated Annual Impact',
      fraudSavings: 'Estimated Internal Fraud Savings',
      fraudNote: 'Based on 0.8% traditional retail loyalty leakage & unauthorized adjustments',
      auditSavings: 'Reconciliation Hours Reclaimed',
      auditNote: 'Zero spreadsheet disputes between franchisees and partner branches',
      gasSaved: 'Gas Sponsoring Savings',
      gasNote: 'Sub-penny Sui micro-gas sponsored by OctaP engine',
    },
    faq: {
      secNum: '07',
      title: 'Frequently Asked Questions',
      subtitle: 'Everything enterprises, developers, and compliance officers need to know about OctaP.',
      items: [
        {
          q: 'What exactly is Credit-as-a-Service (CaaS)?',
          a: 'Credit-as-a-Service allows enterprises to deploy their own closed-loop promotional reward tokens and campaign rules without developing blockchain infrastructure. OctaP handles Move contract execution, gas sponsorship, zkLogin authentication, and ledger auditability out-of-the-box.',
        },
        {
          q: 'Do end-customers or cashiers need crypto wallets or SUI coins?',
          a: 'No. End-users experience OctaP as a normal Web2 app. They sign in using their phone number or Google account via Enoki zkLogin. All network gas fees are 100% sponsored by the OctaP relayer, meaning users never see gas fees, private keys, or wallet extensions.',
        },
        {
          q: 'Can points from one merchant be used at another merchant?',
          a: 'No. OctaP strictly enforces tenant isolation (LI-1 in project scope). Lotus Mart Petals exist as separate Move Coin Objects from Phố Cà Phê Beans. Points cannot be traded across brands or redeemed outside the issuing merchant’s authorized reward catalog.',
        },
        {
          q: 'Can reward points be cashed out into fiat currency?',
          a: 'No. Under regulatory exclusion LI-2, OctaPoints and merchant tokens are promotional non-cash reward credits. They cannot be converted, withdrawn, or cashed out into fiat, ensuring full compliance with consumer promotion laws.',
        },
        {
          q: 'How does the AI Model Context Protocol (MCP) server work?',
          a: 'OctaP exposes an MCP server compliant with Anthropic and OpenAI tool-calling specifications. Authorized AI agents can check member balances, verify redemption rules, or simulate tier upgrades within granular Role-Based Access Control (RBAC) boundaries.',
        },
        {
          q: 'How does OctaP prevent internal employee point theft?',
          a: 'Traditional databases allow rogue developers or database administrators to inject points with raw SQL updates. On OctaP, points can only be minted through verified Move contracts signed by authorized multi-sig merchant keys, and every issuance leaves an unalterable Sui cryptographic digest.',
        },
      ],
    },
    demoAccounts: {
      title: 'Interactive Test Environment & Personas',
      subtitle: 'OctaP provides fully interactive demo accounts to experience the platform from every stakeholder perspective.',
      passwordHint: 'Password for all accounts: octap123',
      cards: [
        {
          role: 'Platform Admin',
          email: 'admin@octap.io',
          desc: 'Global oversight: onboard merchants, approve vouchers, inspect Sui audit logs.',
          cta: 'Launch Admin Portal',
          link: '/login?email=admin@octap.io',
        },
        {
          role: 'Store Owner (Lotus Mart)',
          email: 'owner@lotusmart.vn',
          desc: 'Store management: configure campaigns, issue points, manage developer API keys.',
          cta: 'Launch Merchant Dashboard',
          link: '/login?email=owner@lotusmart.vn',
        },
        {
          role: 'Store Cashier (POS)',
          email: 'cashier@lotusmart.vn',
          desc: 'Restricted cashier interface: instant point issuance at POS counter without admin settings.',
          cta: 'Launch Cashier Terminal',
          link: '/login?email=cashier@lotusmart.vn',
        },
        {
          role: 'Shopper Mobile Wallet',
          email: '0901 234 567',
          desc: 'Customer mobile wallet preview: earn points, browse rewards, and display redeem QR.',
          cta: 'Open Customer Wallet',
          link: '/wallet',
        },
      ],
    },
    cta: {
      title: 'Ready to Modernize Your Loyalty Infrastructure?',
      subtitle: 'Join leading retail brands that trust OctaP to deliver cryptographic certainty, zero fraud, and seamless customer experiences.',
      btnLaunch: 'Launch OctaP Management Console',
      btnWallet: 'Test End-User Wallet Demo',
      btnContact: 'Explore Developer Documentation',
    },
    footer: {
      tagline: 'Enterprise Credit-as-a-Service built on the Sui blockchain.',
      networkStatus: 'Sui Testnet / Mainnet: Operational',
      colProduct: 'Platform',
      features: 'Features & Architecture',
      tenantIsolation: 'Tenant Isolation',
      zkLogin: 'Enoki zkLogin',
      mcpServer: 'AI MCP Server',
      colDevelopers: 'Developers',
      sdk: 'TypeScript SDK',
      apiDocs: 'API Reference',
      suiExplorer: 'Sui Ledger Explorer',
      sandbox: 'Mock Sandbox',
      colEcosystem: 'Ecosystem',
      lotusMart: 'Lotus Mart Loyalty',
      phoCaPhe: 'Phố Cà Phê',
      saigonBooks: 'Sài Gòn Books',
      customerWallet: 'Shopper Mobile App',
      copyright: '© 2026 OctaP (OctaPoint) Network. All rights reserved. Built on Sui.',
    },
  },
  vi: {
    nav: {
      features: 'Tính năng',
      whyOctap: 'Vì sao chọn OctaP',
      architecture: 'Kiến trúc',
      developers: 'Nhà phát triển',
      ecosystem: 'Đối tác',
      calculator: 'Ước tính ROI',
      faq: 'Hỏi đáp',
      login: 'Đăng nhập',
      wallet: 'Thử ví thành viên',
      dashboard: 'Vào quản trị',
      demoAccounts: 'Tài khoản mẫu',
    },
    hero: {
      badge: 'Nền tảng Tín nhiệm Loyalty Doanh nghiệp (CaaS) trên Sui',
      h1Lead: 'Hạ tầng Điểm thưởng',
      h1Accent: 'Chống Gian lận',
      h1Tail: 'cho Doanh nghiệp Hiện đại.',
      description:
        'Triển khai điểm thưởng cô lập đa doanh nghiệp với bằng chứng mật mã tức thì. Xóa bỏ rủi ro gian lận cơ sở dữ liệu nội bộ, triệt tiêu tranh chấp đối soát và đem lại trải nghiệm Web2 thân thiện nhờ công nghệ Sui zkLogin và tài trợ phí gas 100%.',
      ctaPrimary: 'Vào Trang Quản Trị Đối Tác',
      ctaSecondary: 'Trải Nghiệm Ví Người Dùng',
      ctaDocs: 'Xem Tài Liệu SDK & MCP',
      subtext: 'Không cần ví crypto · Xác nhận giao dịch <400ms · 100% miễn phí gas cho người dùng',
      liveSimulatorTitle: 'Mô phỏng POS & Chuỗi khối Sui Trực tiếp',
      merchantSelectLabel: 'Chọn Doanh nghiệp Tích điểm',
      customerPhoneLabel: 'Số điện thoại khách hàng (zkLogin)',
      billAmountLabel: 'Giá trị hóa đơn thanh toán (₫)',
      btnSimulate: 'Mô phỏng Tích điểm POS',
      minting: 'Đang ghi nhận lên Sui...',
      resultIssued: 'Đã đúc điểm an toàn trên Sui Move',
      suiTxStreamTitle: 'Luồng Giao Dịch Sui Thời Gian Thực',
      sponsoredTag: 'Tài trợ gas: 0 SUI',
      verifiedDigest: 'Mã xác thực Sui',
      clickToVerify: 'Bấm để tra cứu chi tiết bằng chứng',
    },
    metrics: {
      isolationVal: '100%',
      isolationLbl: 'Cô lập Doanh nghiệp',
      isolationSub: 'Phân tách đối tượng Move tuyệt đối',
      finalityVal: '<400ms',
      finalityLbl: 'Tốc độ Đồng thuận',
      finalitySub: 'Xác nhận tức thì tại quầy thu ngân',
      gasVal: '0 ₫',
      gasLbl: 'Phí Gas Người Dùng',
      gasSub: 'Nền tảng tài trợ toàn bộ chi phí chuỗi',
      fraudVal: '0%',
      fraudLbl: 'Gian lận Dữ liệu Nội bộ',
      fraudSub: 'Bất biến nhờ mật mã phi tập trung',
      integrationVal: '15 phút',
      integrationLbl: 'Thời gian Tích hợp POS',
      integrationSub: 'Bộ công cụ TypeScript SDK & REST API',
    },
    why: {
      secNum: '01',
      title: 'Bước Chuyển Mình Sang Điểm Thưởng Mật Mã',
      subtitle:
        'Cơ sở dữ liệu truyền thống dễ bị chỉnh sửa ngầm, nhân viên lạm quyền và đối soát hóa đơn tranh chấp. Các giải pháp Web3 cũ lại quá phức tạp. OctaP kết nối hoàn hảo cả hai thế giới.',
      tableTitle: 'So Sánh Năng Lực Hạ Tầng',
      colFeature: 'Tiêu chí so sánh',
      colTrad: 'Cơ sở dữ liệu tập trung',
      colUrbox: 'Sàn Voucher B2C trung gian',
      colTalon: 'SaaS Khuyến mãi Web2',
      colOctap: 'OctaP CaaS (Blockchain Sui)',
      features: [
        {
          name: 'Tính minh bạch kiểm toán',
          trad: 'Nhật ký SQL nội bộ; quản trị viên DB có thể sửa đổi',
          urbox: 'Hệ thống đóng; đối tác bắt buộc tin tưởng máy chủ UrBox',
          talon: 'Nhật ký riêng tư của bên thứ ba; vẫn chịu rủi ro DB nội bộ',
          octap: 'Bằng chứng mã băm Sui công khai; bất biến toán học',
        },
        {
          name: 'Cô lập điểm giữa các thương hiệu',
          trad: 'Bảng dữ liệu phức tạp; rủi ro rò rỉ hoặc cộng nhầm điểm',
          urbox: 'Chợ voucher chung; thương hiệu mất quyền kiểm soát độc lập',
          talon: 'Luật phần mềm ảo; không có ranh giới mật mã',
          octap: 'Mỗi thương hiệu sở hữu Move Coin Object và kho quỹ riêng',
        },
        {
          name: 'Trải nghiệm người dùng cuối',
          trad: 'Phải cài app riêng, tốn chi phí OTP SMS, quên mật khẩu',
          urbox: 'Bị điều hướng sang ứng dụng voucher trung gian',
          talon: 'Yêu cầu tự xây dựng toàn bộ frontend',
          octap: 'Không rào cản Web3: Đăng nhập SĐT / Google qua zkLogin',
        },
        {
          name: 'Chi phí hạ tầng & giao dịch',
          trad: 'Chi phí duy trì máy chủ, bản quyền cơ sở dữ liệu lớn',
          urbox: 'Phí hoa hồng cao trên từng voucher bán ra',
          talon: 'Phí thuê bao phần mềm doanh nghiệp đắt đỏ',
          octap: 'Phí gas siêu nhỏ của Sui được tài trợ 100% bởi OctaP',
        },
        {
          name: 'Tích hợp Trí tuệ Nhân tạo (MCP)',
          trad: 'Không có hoặc phải tự viết webhook',
          urbox: 'Không hỗ trợ giao thức AI agent',
          talon: 'Chỉ có REST webhook; không hỗ trợ ngữ cảnh cho bot',
          octap: 'Sẵn sàng giao thức chuẩn Model Context Protocol (MCP)',
        },
        {
          name: 'Tuân thủ pháp lý & Quy đổi tiền mặt',
          trad: 'Dễ vướng tranh chấp pháp lý bảo vệ người tiêu dùng',
          urbox: 'Mô hình mua bán voucher quà tặng',
          talon: 'Phụ thuộc thiết lập thủ công của doanh nghiệp',
          octap: 'Điểm thưởng nội bộ không thể rút tiền mặt; tuân thủ chuẩn',
        },
      ],
    },
    pillars: {
      secNum: '02',
      title: 'Các Trụ Cột Kiến Trúc Của OctaP',
      subtitle: 'Được thiết kế chuyên biệt cho độ tin cậy doanh nghiệp, tốc độ xử lý hàng nghìn giao dịch mỗi giây và bảo mật mật mã tuyệt đối.',
      items: [
        {
          id: 'isolation',
          tag: 'FE-01 · KIẾN TRÚC LÕI',
          title: 'Cô Lập Điểm Thưởng Độc Lập Theo Doanh Nghiệp',
          desc: 'Mỗi thương hiệu vận hành Move Module và quỹ điểm độc lập trên Sui. Điểm của Lotus Mart không thể đem sang Phố Cà Phê, tránh pha loãng giá trị tài chính. Nghiêm cấm quy đổi tiền mặt.',
          badge: 'Hợp đồng Move',
        },
        {
          id: 'zklogin',
          tag: 'FE-02 · TRẢI NGHIỆM TIỆN LỢI',
          title: 'Đăng Nhập zkLogin & Tài Trợ Gas 100%',
          desc: 'Người tiêu dùng không bao giờ phải giữ khóa riêng tư, cụm từ khôi phục hay ví crypto. Khách hàng chỉ cần đăng nhập số điện thoại hoặc Google qua Enoki zkLogin.',
          badge: 'Enoki zkLogin',
        },
        {
          id: 'pos',
          tag: 'FE-03 · TÍCH ĐIỂM TỨC THÌ',
          title: 'Tích Hợp POS & Phát Hành Điểm <400ms',
          desc: 'Cộng điểm tự động tại quầy thu ngân với độ trễ chưa đầy 400 mili-giây. Hỗ trợ quét mã vạch hóa đơn in sẵn và quét mã QR tại chỗ mà không gây ùn tắc quầy.',
          badge: 'POS & Bán lẻ',
        },
        {
          id: 'mcp',
          tag: 'FE-04 · TỰ ĐỘNG HÓA AI',
          title: 'Máy Chủ Model Context Protocol (MCP)',
          desc: 'Cho phép các trợ lý AI (Claude, Gemini, ChatGPT) truy vấn số dư thành viên, đề xuất voucher cá nhân hóa và quản lý chiến dịch với phân quyền RBAC nghiêm ngặt.',
          badge: 'Chuẩn Anthropic MCP',
        },
        {
          id: 'sdk',
          tag: 'FE-05 · DÀNH CHO LẬP TRÌNH VIÊN',
          title: 'Bộ Công Cụ TypeScript SDK Toàn Diện',
          desc: 'Tích hợp hệ thống ERP, máy POS, website bán hàng hay ứng dụng Flutter di động chỉ với 4 dòng mã TypeScript. Đi kèm bộ kiểm thử giả lập sẵn có.',
          badge: 'TypeScript SDK',
        },
        {
          id: 'audit',
          tag: 'FE-06 · BẰNG CHỨNG KIỂM TOÁN',
          title: 'Tra Cứu Bằng Chứng Mật Mã Minh Bạch',
          desc: 'Mọi thao tác tích điểm, áp dụng nhân đôi điểm chiến dịch, đổi voucher và điều chỉnh điểm đều tạo mã xác thực Sui công khai để kiểm toán viên dễ dàng đối soát.',
          badge: 'Bất biến & Xác thực',
        },
      ],
    },
    architecture: {
      secNum: '03',
      title: 'Quy Trình Xử Lý Mật Mã Khép Kín',
      subtitle: 'Cách OctaP biến một giao dịch mua hàng quen thuộc thành sự kiện điểm thưởng bất biến trên blockchain không một chút ma sát.',
      steps: [
        {
          step: '1',
          title: 'Khách hàng thanh toán',
          actor: 'Người mua / Thu ngân',
          desc: 'Khách hàng đọc số điện thoại hoặc thu ngân quét mã vạch hóa đơn thanh toán tại quầy POS.',
        },
        {
          step: '2',
          title: 'Xác thực zkLogin',
          actor: 'Hạ tầng Enoki zkLogin',
          desc: 'Công nghệ Zero-Knowledge tạo chữ ký mật mã an toàn tức thì từ tài khoản Google hoặc SĐT của khách.',
        },
        {
          step: '3',
          title: 'Cổng OctaP CaaS',
          actor: 'Động cơ API & MCP',
          desc: 'Kiểm tra luật chiến dịch (ví dụ nhân 1.5× hạng Vàng) và bao gói giao dịch tài trợ phí gas.',
        },
        {
          step: '4',
          title: 'Xác nhận trên Sui',
          actor: 'Move Isolated Coin Object',
          desc: 'Thuật toán đồng thuận xử lý việc đúc hoặc trừ điểm trực tiếp trên Move module của đối tác dưới 400ms.',
        },
        {
          step: '5',
          title: 'Bằng chứng bất biến',
          actor: 'Mã băm giao dịch Sui',
          desc: 'Mã băm giao dịch được lưu vĩnh viễn cho mục đích kiểm toán, chống gian lận và hiển thị trên ví người dùng.',
        },
      ],
    },
    developers: {
      secNum: '04',
      title: 'Trải Nghiệm Nhà Phát Triển: SDK & MCP',
      subtitle: 'Xây dựng luồng tích điểm doanh nghiệp chỉ trong vài phút bằng TypeScript hoặc kết nối trợ lý AI qua giao thức Model Context Protocol.',
      tabs: {
        earn: '1. Tích điểm POS (Earn)',
        redeem: '2. Đổi điểm zkLogin',
        mcp: '3. Trợ lý AI (MCP)',
        verify: '4. Kiểm toán chuỗi',
      },
      btnRun: 'Mô phỏng Lời gọi SDK',
      outputTitle: 'Phản hồi SDK thực tế (JSON)',
    },
    ecosystem: {
      secNum: '05',
      title: 'Mạng Lưới Đối Tác Tiêu Biểu',
      subtitle: 'Các thương hiệu dẫn đầu trong ngành bán lẻ tiêu dùng, ẩm thực, nhà sách và nghỉ dưỡng đang vận hành điểm thưởng trên OctaP.',
      badgeActive: 'Đang hoạt động',
      btnTestStore: 'Xem mẫu giao diện',
      tenantNotice: 'Cam kết cô lập tuyệt đối: Điểm của mỗi thương hiệu là độc lập và không thể quy đổi ra tiền mặt.',
    },
    calculator: {
      secNum: '06',
      title: 'Ước Tính Hiệu Quả & Giảm Gian Lận',
      subtitle: 'Ước lượng khoản ngân sách tiết kiệm hàng năm khi chuyển từ cơ sở dữ liệu truyền thống sang hạ tầng OctaP CaaS.',
      membersLabel: 'Số lượng thành viên hoạt động hàng tháng',
      txsLabel: 'Số lượng giao dịch tích/đổi điểm mỗi tháng',
      basketLabel: 'Giá trị đơn hàng trung bình (₫)',
      resultsTitle: 'Hiệu quả ước tính hàng năm',
      fraudSavings: 'Ngân sách tránh thất thoát gian lận',
      fraudNote: 'Dựa trên tỷ lệ hao hụt & chỉnh sửa điểm bất thường trung bình 0.8% trong ngành bán lẻ',
      auditSavings: 'Thời gian đối soát kế toán thu hồi',
      auditNote: 'Không còn tranh chấp số liệu bảng tính giữa các chi nhánh và chuỗi nhượng quyền',
      gasSaved: 'Chi phí gas được nền tảng tài trợ',
      gasNote: 'Toàn bộ chi phí gas siêu nhỏ của Sui được hệ thống OctaP đài thọ',
    },
    faq: {
      secNum: '07',
      title: 'Câu Hỏi Thường Gặp',
      subtitle: 'Mọi thắc mắc của doanh nghiệp, lập trình viên và bộ phận tuân thủ pháp lý về nền tảng OctaP.',
      items: [
        {
          q: 'Mô hình Credit-as-a-Service (CaaS) là gì?',
          a: 'Credit-as-a-Service cho phép doanh nghiệp tự sở hữu điểm thưởng điện tử và quy tắc chiến dịch riêng mà không cần phải tự lập trình blockchain. OctaP đảm nhận toàn bộ hợp đồng Move, tài trợ phí gas, đăng nhập zkLogin và đối soát sổ cái.',
        },
        {
          q: 'Khách hàng hoặc nhân viên thu ngân có cần ví crypto hay đồng SUI không?',
          a: 'Hoàn toàn không. Người dùng trải nghiệm như ứng dụng Web2 thông thường qua số điện thoại hoặc tài khoản Google. Tất cả phí gas giao dịch đều do OctaP tài trợ 100%, không bao giờ xuất hiện ví tiền mã hóa hay cụm từ khóa bí mật.',
        },
        {
          q: 'Điểm của thương hiệu này có dùng được ở thương hiệu khác không?',
          a: 'Không. OctaP tuân thủ nghiêm ngặt nguyên tắc cô lập doanh nghiệp (LI-1 trong tài liệu phạm vi). Điểm Sen của Lotus Mart là Move Coin Object tách biệt hoàn toàn với điểm của Phố Cà Phê, không thể tiêu chéo để bảo vệ ngân sách từng thương hiệu.',
        },
        {
          q: 'Điểm thưởng có được đổi thành tiền mặt không?',
          a: 'Không. Điểm thưởng trên OctaP là điểm tri ân khách hàng phi tiền tệ theo quy định LI-2. Hệ thống không hỗ trợ bất kỳ tính năng rút tiền hay quy đổi sang tiền mặt nào, đảm bảo 100% tuân thủ pháp luật khuyến mãi hiện hành.',
        },
        {
          q: 'Máy chủ Model Context Protocol (MCP) hoạt động như thế nào?',
          a: 'OctaP cung cấp máy chủ MCP tương thích với chuẩn gọi công cụ của Anthropic và OpenAI. Các trợ lý AI có thể tra cứu số dư thành viên, kiểm tra điều kiện voucher hoặc đề xuất ưu đãi trong phạm vi phân quyền RBAC an toàn.',
        },
        {
          q: 'OctaP chống gian lận điểm nội bộ ra sao?',
          a: 'Ở cơ sở dữ liệu truyền thống, nhân viên IT hay quản trị viên có thể tự cập nhật SQL để cộng điểm khống. Trên OctaP, điểm chỉ có thể sinh ra qua hợp đồng Move có chữ ký ủy quyền, và mọi giao dịch đều để lại mã băm Sui công khai không thể xóa bỏ.',
        },
      ],
    },
    demoAccounts: {
      title: 'Môi Trường Trải Nghiệm & Các Vai Trò',
      subtitle: 'OctaP thiết lập sẵn các tài khoản demo đầy đủ để bạn trải nghiệm trọn vẹn mọi góc nhìn của nền tảng.',
      passwordHint: 'Mật khẩu chung cho tất cả tài khoản: octap123',
      cards: [
        {
          role: 'Quản trị viên Hệ thống (OctaP Admin)',
          email: 'admin@octap.io',
          desc: 'Quản lý toàn sàn: duyệt đối tác mới, phê duyệt voucher, kiểm tra sổ cái kiểm toán Sui.',
          cta: 'Vào Cổng Admin',
          link: '/login?email=admin@octap.io',
        },
        {
          role: 'Chủ Cửa Hàng (Lotus Mart)',
          email: 'owner@lotusmart.vn',
          desc: 'Quản lý thương hiệu: thiết lập chiến dịch điểm, quản lý nhân sự, cấp mã API và công cụ AI.',
          cta: 'Vào Dashboard Chủ Quán',
          link: '/login?email=owner@lotusmart.vn',
        },
        {
          role: 'Thu Ngân Quầy POS (Lotus Mart)',
          email: 'cashier@lotusmart.vn',
          desc: 'Giao diện tinh gọn cho thu ngân: tích điểm cho khách theo hóa đơn mà không sửa được cấu hình.',
          cta: 'Vào Quầy Thu Ngân',
          link: '/login?email=cashier@lotusmart.vn',
        },
        {
          role: 'Khách Hàng Mua Sắm (Ví Di Động)',
          email: '0901 234 567',
          desc: 'Giao diện điện thoại người tiêu dùng: xem số dư điểm, đổi voucher và xuất mã vạch thanh toán.',
          cta: 'Mở Ví Khách Hàng',
          link: '/wallet',
        },
      ],
    },
    cta: {
      title: 'Sẵn Sàng Nâng Tầm Hạ Tầng Điểm Thưởng Doanh Nghiệp?',
      subtitle: 'Gia nhập mạng lưới các thương hiệu bán lẻ hàng đầu tin tưởng OctaP để đạt sự minh bạch mật mã, xóa tan gian lận và tối ưu chi phí.',
      btnLaunch: 'Khởi Chạy Bảng Điều Khiển OctaP',
      btnWallet: 'Trải Nghiệm Ví Người Dùng',
      btnContact: 'Khám Phá Tài Liệu Lập Trình',
    },
    footer: {
      tagline: 'Hạ tầng Tín nhiệm & Điểm thưởng Doanh nghiệp trên Blockchain Sui.',
      networkStatus: 'Sui Testnet / Mainnet: Hoạt động ổn định',
      colProduct: 'Nền tảng',
      features: 'Tính năng & Kiến trúc',
      tenantIsolation: 'Cô lập Doanh nghiệp',
      zkLogin: 'Đăng nhập Enoki zkLogin',
      mcpServer: 'Máy chủ AI MCP',
      colDevelopers: 'Nhà phát triển',
      sdk: 'TypeScript SDK',
      apiDocs: 'Tài liệu API',
      suiExplorer: 'Tra cứu Sổ cái Sui',
      sandbox: 'Môi trường Thử nghiệm',
      colEcosystem: 'Hệ sinh thái',
      lotusMart: 'Siêu thị Lotus Mart',
      phoCaPhe: 'Phố Cà Phê',
      saigonBooks: 'Nhà sách Sài Gòn',
      customerWallet: 'Ứng dụng Ví Khách hàng',
      copyright: '© 2026 Mạng lưới OctaP (OctaPoint). Giữ toàn quyền. Xây dựng trên Sui.',
    },
  },
};
